#!/bin/bash
set +e

# Create the temporarily directory if neccessary
if [ ! -d /tmp/.journey ]; then
    mkdir -p /tmp/.journey
    mkdir -p /tmp/.journey/nginx/proxy
    mkdir -p /tmp/.journey/nginx/body
    mkdir -p /tmp/.journey/nginx/fastcgi
    mkdir -p /tmp/.journey/nginx/uwsgi
    mkdir -p /tmp/.journey/nginx/scgi
fi

echo "Starting php-fpm..."
php-fpm7.4 -c /code/.fun/root/usr/lib/php/7.4/php.ini-production \
    -y /code/.fun/root/etc/php/7.4/fpm/php-fpm.conf

echo "Starting nginx..."
nginx -c /code/.fun/root/etc/nginx/nginx.conf

sleep 5

while true
do
    echo "Checking..."

    nginx_server=`ps aux | grep nginx | grep -v grep`
    if [ ! "$nginx_server" ]; then
        echo "Restarting nginx..."

        nginx -c /code/.fun/root/etc/nginx/nginx.conf
    fi

    php_fpm_server=`ps aux | grep php-fpm | grep -v grep`
    if [ ! "$php_fpm_server" ]; then
        echo "Restarting php-fpm..."

        php-fpm7.4 -c /code/.fun/root/usr/lib/php/7.4/php.ini-production \
            -y /code/.fun/root/etc/php/7.4/fpm/php-fpm.conf
    fi

    sleep 10
done
